import { TradeData, SubscriptionData, NewsItem, MyApartment } from './types'

export const mockTrades: TradeData[] = [
  { dealYear: '2025', dealMonth: '4', dealDay: '28', aptName: '잠실엘스', area: 84.93, floor: 15, dealAmount: '280,000' },
  { dealYear: '2025', dealMonth: '4', dealDay: '22', aptName: '잠실엘스', area: 59.98, floor: 8,  dealAmount: '195,000' },
  { dealYear: '2025', dealMonth: '4', dealDay: '15', aptName: '잠실엘스', area: 84.93, floor: 22, dealAmount: '285,000' },
  { dealYear: '2025', dealMonth: '3', dealDay: '30', aptName: '잠실엘스', area: 114.96, floor: 18, dealAmount: '365,000' },
  { dealYear: '2025', dealMonth: '3', dealDay: '17', aptName: '잠실엘스', area: 84.93, floor: 5,  dealAmount: '272,000' },
  { dealYear: '2025', dealMonth: '3', dealDay: '8',  aptName: '잠실엘스', area: 59.98, floor: 12, dealAmount: '192,000' },
  { dealYear: '2025', dealMonth: '2', dealDay: '25', aptName: '잠실엘스', area: 84.93, floor: 20, dealAmount: '278,000' },
  { dealYear: '2025', dealMonth: '2', dealDay: '14', aptName: '잠실엘스', area: 114.96, floor: 25, dealAmount: '370,000' },
  { dealYear: '2025', dealMonth: '1', dealDay: '20', aptName: '잠실엘스', area: 84.93, floor: 10, dealAmount: '268,000' },
  { dealYear: '2025', dealMonth: '1', dealDay: '7',  aptName: '잠실엘스', area: 59.98, floor: 3,  dealAmount: '188,000' },
]

export const mockSubscriptions: SubscriptionData[] = [
  {
    id: 'sub-001',
    name: '서울 강동구 고덕강일 공공분양',
    location: '서울시 강동구 고덕동',
    startDate: '2025-05-12',
    endDate: '2025-05-16',
    totalCount: 320,
    type: '일반공급',
    status: '진행중',
  },
  {
    id: 'sub-002',
    name: '마포 공덕 SK뷰',
    location: '서울시 마포구 공덕동',
    startDate: '2025-05-20',
    endDate: '2025-05-24',
    totalCount: 180,
    type: '특별공급',
    status: '예정',
  },
  {
    id: 'sub-003',
    name: '서초구 반포 래미안 원베일리 재공고',
    location: '서울시 서초구 반포동',
    startDate: '2025-05-08',
    endDate: '2025-05-10',
    totalCount: 45,
    type: '재공고',
    status: '완료',
  },
  {
    id: 'sub-004',
    name: '은평구 녹번 e편한세상',
    location: '서울시 은평구 녹번동',
    startDate: '2025-06-02',
    endDate: '2025-06-06',
    totalCount: 256,
    type: '일반공급',
    status: '예정',
  },
  {
    id: 'sub-005',
    name: '성동구 금호 힐스테이트',
    location: '서울시 성동구 금호동',
    startDate: '2025-05-28',
    endDate: '2025-06-01',
    totalCount: 98,
    type: '추가청약',
    status: '예정',
  },
  {
    id: 'sub-006',
    name: '노원구 공릉 롯데캐슬',
    location: '서울시 노원구 공릉동',
    startDate: '2025-04-21',
    endDate: '2025-04-25',
    totalCount: 410,
    type: '일반공급',
    status: '완료',
  },
  {
    id: 'sub-007',
    name: '양천구 목동 자이',
    location: '서울시 양천구 목동',
    startDate: '2025-06-16',
    endDate: '2025-06-20',
    totalCount: 140,
    type: '특별공급',
    status: '예정',
  },
  {
    id: 'sub-008',
    name: '광진구 자양 더샵',
    location: '서울시 광진구 자양동',
    startDate: '2025-05-19',
    endDate: '2025-05-23',
    totalCount: 72,
    type: '일반공급',
    status: '예정',
  },
]

export const mockNews: NewsItem[] = [
  {
    id: 'news-001',
    title: '한국은행 기준금리 3.00%로 동결… 부동산 시장 영향은?',
    summary: '한국은행 금융통화위원회가 기준금리를 3.00%로 동결했습니다. 전문가들은 하반기 추가 인하 가능성에 주목하고 있습니다.',
    source: '서울경제',
    date: '2025-05-10',
    url: 'https://www.sedaily.com/',
    category: '금리·대출',
  },
  {
    id: 'news-002',
    title: '잠실 재건축 기대감↑… 엘스·리센츠 매매가 신고가',
    summary: '송파구 잠실동 일대 재건축 추진 기대감이 높아지면서 잠실엘스, 리센츠 아파트가 잇따라 신고가를 기록하고 있습니다.',
    source: '매일경제',
    date: '2025-05-09',
    url: 'https://www.mk.co.kr/',
    category: '재건축·재개발',
  },
  {
    id: 'news-003',
    title: '2025 하반기 서울 공공분양 2만호 공급 예정',
    summary: '국토교통부가 2025년 하반기 서울 공공분양 2만 호 공급 계획을 발표했습니다. 강동·노원·은평구 중심으로 공급 예정.',
    source: '한국경제',
    date: '2025-05-08',
    url: 'https://www.hankyung.com/',
    category: '청약·분양',
  },
  {
    id: 'news-004',
    title: '취득세 중과 완화 법안, 국회 본회의 통과',
    summary: '다주택자 취득세 중과세율 완화 법안이 국회를 통과했습니다. 2주택자 중과 적용 기준이 상향되어 규제지역 매수 부담이 줄어들 전망입니다.',
    source: '조선일보',
    date: '2025-05-07',
    url: 'https://www.chosun.com/',
    category: '세금·규제',
  },
  {
    id: 'news-005',
    title: '서울 아파트 매매 거래량 4개월 연속 증가',
    summary: '4월 서울 아파트 매매 거래량이 5,200건으로 작년 동기 대비 23% 증가했습니다. 강남3구와 마포·용산 선호지역이 거래를 주도하고 있습니다.',
    source: '부동산114',
    date: '2025-05-06',
    url: 'https://www.r114.com/',
    category: '시장동향',
  },
  {
    id: 'news-006',
    title: 'DSR 40% 규제 완화 검토… 실수요자 대출 숨통 트이나',
    summary: '금융당국이 실수요자 보호를 위해 DSR 40% 규제 완화 방안을 검토 중인 것으로 알려졌습니다. 생애최초 구입자 예외 확대가 핵심입니다.',
    source: '이데일리',
    date: '2025-05-05',
    url: 'https://www.edaily.co.kr/',
    category: '금리·대출',
  },
]

export const mockMyApartments: MyApartment[] = [
  {
    id: 'my-001',
    name: '잠실엘스',
    address: '서울시 송파구 잠실동 1-1',
    lawdCd: '11710',
    aptName: '잠실엘스',
    memo: '관심 아파트 - 84㎡ 타겟',
  },
]
